/**
 * Neon Dash — official levels (GENERATED FILE — do not edit by hand).
 * Generated by tools/gen-official-levels.js.  Each level is stored as an
 * NDL1 level code — the exact format users share, import and upload —
 * and is verified completable by the physics bot before shipping.
 */
/* global GD */
GD.register('official', function () {
  'use strict';
  return { levels: [
  {
    "id": "l1",
    "name": "Neon Genesis",
    "author": "NeonDash",
    "difficulty": 0,
    "stars": 1,
    "code": "NDL1:MTtOZW9uIEdlbmVzaXM7TmVvbkRhc2g7MDswOzA7Nmo7ay5jLjA7ay5rLjA7ay5zLjA7MXMuOC40OzF6LmUuNjsxcy5vLjQ7ay4xMC4wO2suMTEuMDsxLjE4LjA7MS4xOS4wOzEuMWEuMDsxLjFiLjA7ay4xaS4wO2suMW8uMDtrLjFwLjA7MWUuMXUuMDtrLjF3LjA7ay4xeC4wO2suMXkuMDtrLjI4LjA7ay4yZy4wO2suMmguMDtrLjJpLjA7ay4zNC4wO2suMzUuMDtrLjM2LjA7ay4zNy4wO2suMzguMDtrLjM5LjA7MWouMzYuMjsyMy4zNi40OzFxLjM1LjM7cy4zaS4wO2suM3EuMDtrLjN3LjA7ay40Mi4wO2suNDMuMDsyLjQ4LjA7Mi40OS4wOzIuNGEuMDsyLjRiLjA7Mi40Yy4wOzIuNGUuMDsyLjRlLjE7Mi40Zi4wOzIuNGYuMTsyLjRnLjA7Mi40Zy4xOzIuNGguMDsyLjRoLjE7Mi40aS4wOzIuNGkuMTsyLjRqLjA7Mi40ai4xOzIuNGsuMDsyLjRrLjE7ay40cy4wO2suNHkuMDtrLjU2LjA7ay41Ny4wO3MuNWYuMDtrLjVtLjA7ay41cy4wO2suNXQuMDtrLjV6LjA7ay42NS4wOzF6LjNtLjg7MXkuNGcuNzsyMi41ay41OzFvLjJpLjM7MjEuMnMuNg:093480df"
  },
  {
    "id": "l2",
    "name": "Circuit Breaker",
    "author": "NeonDash",
    "difficulty": 1,
    "stars": 2,
    "code": "NDL1:MTtDaXJjdWl0IEJyZWFrZXI7TmVvbkRhc2g7MTszOzE7OGM7ay5lLjA7ay5rLjA7ay5xLjA7ay53LjA7ay54LjA7ay4xNC4wO2suMTUuMDtrLjE2LjA7cy4xYy4wO3MuMWkuMDtrLjFxLjA7ay4xci4wOzE4LjF5LjA7ay4yNi4wO2suMmUuMDtrLjJmLjA7ay4ybS4wO2suMm4uMDtrLjJvLjA7MTQuMnUuMDtrLjNjLmQuMjtrLjNrLmQuMjtrLjNtLmQuMjtrLjNuLmQuMjs4LjN1LmQ7OC4zdi5kOzguM3cuZDs4LjN4LmQ7OC4zeS5kOzguM3ouZDs4LjQwLmQ7OC40MS5kOzguNDIuZDs4LjQyLmM7OC40My5kOzguNDMuYzs4LjQ0LmQ7OC40NC5jOzguNDUuZDs4LjQ1LmM7MTUuNDguYjsxNy40bC4wO2suNHMuMDtrLjR0LjA7ay40dS4wO2suNHYuMDtrLjR3LjA7MWouNHUuMjsxZS41Mi4wO2suNTQuMDtrLjU1LjA7ay41Ni4wO3MuNWcuMC4wLjhvdzszLjVvLjQ7My41cC40OzMuNXEuNDszLjVyLjQ7My41cy40O2wuNXEuMDtrLjYwLjA7ay42MS4wO2suNjguMDtrLjZlLjA7ay42Zi4wO3MuNm0uMDtrLjZzLjA7di42eS4wO2suNzQuMDtrLjc1LjA7ay43Yy4wO2suN2kuMDtrLjdqLjA7ay43ay4wOzF4LjMwLjY7MXkuNDQuNzsyMS41YS41OzFvLjJzLjQ7MXouNzguNg:5f6205ec"
  },
  {
    "id": "l3",
    "name": "Voltage",
    "author": "NeonDash",
    "difficulty": 2,
    "stars": 4,
    "code": "NDL1:MTtWb2x0YWdlO05lb25EYXNoOzI7MjsyOzlnO2suYy4wO2suaS4wO2suby4wO2sucC4wO3Mudy4wO2suMTIuMDtrLjEzLjA7ay4xNC4wO3QuMWIuMDtrLjFpLjA7ay4xby4wO2suMXcuMDtrLjF4LjA7ay4xeS4wO2suMXouMDtrLjIwLjA7ay4yMS4wO2suMjIuMDtrLjIzLjA7ay4yNC4wO2suMjUuMDsxai4xeS4yOzFqLjIyLjM7MTQuMmcuMDtrLjJ3LmQuMjtzLjMyLmQ7ay4zOC5kLjI7ay4zOS5kLjI7di4zZi5kO2suM2wuZC4yOzMuM3MuZDszLjN0LmQ7My4zdS5kOzMuM3YuZDszLjN3LmQ7My4zeC5kOzMuM3kuZDszLjN6LmQ7My40MC5kOzMuNDEuZDszLjQyLmQ7My40Mi5jOzMuNDMuZDszLjQzLmM7My40NC5kOzMuNDQuYzszLjQ1LmQ7My40NS5jOzE1LjQ5LmI7MWUuNG0uMDtrLjRvLjA7ay40cC4wO2suNHEuMDtrLjRyLjA7ay40cy4wO2suNHQuMDsxai40cS4zO3MuNTAuMDtrLjU2LjA7ay41Yy4wO3MuNWguMC4wLjhvdztrLjVxLjA7ay41ci4wOzcuNXkuNDs3LjV6LjQ7Ny42MC40OzcuNjEuNDs3LjYyLjQ7Ny42My40OzcuNjQuNDtsLjYxLjA7ay42Yy4wO2suNmkuMDtrLjZvLjA7ay42cC4wO2suNnEuMDt0LjZ4LjA7ay43NC4wO2suN2EuMDt2LjdnLjA7di43bC4wO2suN3IuMDtrLjdzLjA7cy43ei4wO2suODYuMDtrLjg3LjA7ay44OC4wOzFlLjhmLjA7ay44aC4wO2suOGkuMDtrLjhqLjA7ay44cy4wO2suOHkuMDtrLjk2LjA7ay45Ny4wOzF4LjJpLjU7MjIuNWsuNzsxby44Yy42:1f3a2a7c"
  },
  {
    "id": "l4",
    "name": "Hyperdrive",
    "author": "NeonDash",
    "difficulty": 4,
    "stars": 8,
    "code": "NDL1:MTtIeXBlcmRyaXZlO05lb25EYXNoOzM7NDs0O2I0O2suYy4wO2suaS4wO2suby4wO2sudS4wO2sudi4wO3MuMTIuMDtrLjE4LjA7ay4xOS4wO2suMWEuMDt0LjFoLjA7MTguMW8uMDtrLjF3LjA7ay4yNC4wO2suMjUuMDtrLjJjLjA7ay4yZC4wO2suMmUuMDtzLjJsLjA7MWUuMnQuMDtrLjJ2LjA7ay4ydy4wO2suMnguMDtrLjJ5LjA7MTQuM2EuMDtrLjNxLmQuMjtrLjN5LmQuMjtzLjQ2LmQ7ay40ZS5kLjI7ay40Zi5kLjI7di40bS5kO3MuNHQuZC4wLjhvdztrLjUyLmQuMjs1LjVjLmQ7NS41ZC5kOzUuNWUuZDs1LjVmLmQ7NS41Zy5kOzUuNWguZDs1LjVpLmQ7NS41ai5kOzUuNWsuZDs1LjVrLmM7NS41bC5kOzUuNWwuYzs1LjVtLmQ7NS41bS5jOzUuNW4uZDs1LjVuLmM7MTUuNXIuYjsxOS42NC4wO2suNmUuMDtrLjZvLjA7ay42cC4wO3MuNnouMDtrLjdhLjA7ay43Yi4wO2suN2MuMDsxZS43bi4wO2suN3AuMDtrLjdxLjA7ay43ci4wO2suN3MuMDtrLjd0LjA7ay43dS4wOzE3Ljg3LjA7ay44Zy4wO2suOG0uMDtzLjh0LjA7ay45MC4wO2suOTEuMDt2Ljk4LjA7di45ZC4wO2suOWsuMDtrLjlsLjA7ay45bS4wO3MuOXUuMC4wLjhvdztrLmE0LjA7ay5hYS4wO3UuYWkuMDtrLmFxLjA7ay5hci4w:6aec246f"
  }
] };
});
